---
- hosts: 127.0.0.1
  roles:
    - role: collivier.xtesting
      suites:
        - repo: opnfv
          container: xtesting
          tag: gambia
          tests:
            - first
            - second
            - third
            - fourth
            - fifth
